### ISSUE TITLE
Disable trust anchor 

### ISSUE THREAD

**Issue by roysG** [OPEnSLab-OSU/SSLClient#61] opened 2022-01-02 23:13 UTC
As i understand the trust anchor working according my domain certificate.
As i understand, In case the domain ssl is expire, than the trust anchor will not work and deny the connection until i it be updated to the new ssl certificate.

In my case i do not have the option to updating the trust anchor. 
How can i disable it?  

I am using in self signed certificate

**Comment by prototypicalpro** [comment] 2022-01-03 00:50
This is a duplicate of #22. I don't have the bandwidth to implement the fix proposed in that issue, but I'd be happy to review a PR on it.

**Closed by prototypicalpro** 2022-01-03 00:50 UTC
Labels: question

**Comment by roysG** [comment] 2022-01-03 03:21
Do i need to uodate the trust anchor manually, in case the ssl certificate
is upated after a year?

**Comment by marcelstoer** [comment] 2022-04-08 19:59
Depends on what you mean by "manually". For devices out in the field you would normally implement some form of OTA (over the air update). You will then be able to have the device update itself i.e. it'll fetch the new firmware that contains the updated trust anchors.
